### ISSUE TITLE
Duplication of style definitions

### ISSUE THREAD

**Issue by ratrun** [osm2vectortiles/tileserver-gl-light#2]
Can you please explain the relationship of the styles contained in here to those maintained under https://github.com/osm2vectortiles/mapbox-gl-styles ?
Wouldn't it be possible and better to reference a branch of  https://github.com/osm2vectortiles/mapbox-gl-styles here as a git submodule?

**Comment by lukasmartinelli** [comment]
> Can you please explain the relationship of the styles contained in here to those maintained under https://github.com/osm2vectortiles/mapbox-gl-styles ?

Good insight.
There are no styles in osm2vectortiles (or are there?) but you are correct they are for example duplicated in https://github.com/osm2vectortiles/tileserver-gl-light.
In the gh-pages branch we point to the raw style object via HTTP in the style GitHub repo. 

@klokan suggested this before  - it would be a good change.

**Comment by klokan** [comment]
To be done probably together with the tileserver-gl-light integration back into the tileserver-gl master (planned before v1.0 release on FOSS4G https://github.com/klokantech/tileserver-gl/issues/27).

In TileServer-GL the styles, glyphs and sprites are not part of the git repo with the software itself (where it does not belong IMHO), but are downloaded from a separate repo on start, if not provided by the user. Right now it is https://github.com/klokantech/tileserver-gl-data

MapBox has/had their styles in NPM - to simplify the deployment. We may probably follow the same principle - where styles are required by the software via npm.

What do you think, guys?

**Comment by lukasmartinelli** [comment]
> To be done probably together with the tileserver-gl-light integration back into the tileserver-gl master (planned before v1.0 release on FOSS4G klokantech#27).
> 
> In TileServer-GL the styles, glyphs and sprites are not part of the git repo with the software itself (where it does not belong IMHO), but are downloaded from a separate repo on start, if not provided by the user. Right now it is https://github.com/klokantech/tileserver-gl-data
> 
> MapBox has/had their styles in NPM - to simplify the deployment. We may probably follow the same principle - where styles are required by the software via npm.
> 
> What do you think, guys?

Yes! But let's rename https://github.com/osm2vectortiles/mapbox-gl-styles to just **gl-styles**.
So in the future we can add our own styles as well.
And then publish it to npm and require it inside tileserver-gl-light.

The **gl-styles** should point to the CDN (and tileserver-gl-light then replaces that with the local server). This way we can also use them directly on OSM2VectorTiles.


>  TileServer-GL the styles, glyphs and sprites are not part of the git repo with the software itself (where it does not belong IMHO), but are downloaded from a separate repo on start, if not provided by the user. Right now it is https://github.com/klokantech/tileserver-gl-data

Yes I understand this approach, it really makes sense from an advanced user perspective.
What we didn't like is that it makes it harder to get started (cannot just do `npm install` and then `tileserver-gl-light`)

**Comment by klokan** [comment]
I am glad you favour the idea of separating the styles/glyphs/sprites from the tileserver code.

In the rewritten tileserver-gl-light - the simple `npm install` and `tileserver-gl-light filename.mbtiles` should be preserved. I like it too.

**Comment by klokan** [comment]
The initial version of the repo with styles and glyphs is now in npm - and made from this repository:
https://github.com/klokantech/tileserver-gl-styles
This is a dependency in tileserver-gl and tileserver-gl-light.

The best long term approach would be to have a repo osm2vectortiles/osm2vectortiles-gl-styles which contains correct JSON styles and required resource for deploy in tileserver-gl.
This should probably happen with OSM2VectorTiles V3 release.

Closing this ticket. Please continue on klokantech/tileserver-gl or osm2vectortiles/osm2vectortiles.

**Comment by klokan** [comment]
Let's continue discussion under https://github.com/osm2vectortiles/osm2vectortiles/issues/415
