### ISSUE TITLE
Styles not working with forwarded https

### ISSUE THREAD

**Issue by efi** [osm2vectortiles/tileserver-gl-light#3]
I am using haproxy to allow access to the tileserver via http and https. The proxy transparently handles the SSL part.

The styles always return the URLs of the http versions of the assets (for "data/osm2vectortiles.json" and so on).

It would be great if they just returned "//example.com/styles/bright/sprite" instead of "http://example.com/styles/bright/sprite"

Would that be possible?

**Comment by efi** [comment]
I just fiddled around with the osm2vectortiles file and it seems that mapbog-gl-js then does not support a protocol-less tile URL template like:
```{"tiles":["//example.com/data/osm2vectortiles/{z}/{x}/{y}.pbf"]...```
So either somethig over there woud have to be changed or tileserver-gl-light should have alterntive styles `basic_https` and `bright_https` that point to the https-version of all URLs.

What do you think?

**Comment by lukasmartinelli** [comment]
> What do you think?

Thanks for diggint into it.
The quickest way for you is to just copy - paste the style and change the endpoint.
Styles do not necessarily need to be served by tileserver - only meant for glyphs/pbfs.

**Comment by klokan** [comment]
The latest tileserver-gl runs on https very well and @klokantech is using it this way - by linking the vector tiles in style JSON with https protocol (this is automated).

Once the tileserver-gl-light is part of the tileserver-gl (https://github.com/klokantech/tileserver-gl/issues/27) the relevant changes in the code will propagate here too and this ticket can be closed.

I suggest to test true "tileserver-gl" and if you discover an issue there - propose the changes to that repository now.

**Comment by klokan** [comment]
Closing as resolved. Please continue on klokantech/tileserver-gl.
