### ISSUE TITLE
More command line options

### ISSUE THREAD

**Issue by efi** [osm2vectortiles/tileserver-gl-light#4]
I'm not sure whether these should be individual feature requests, but I would like to have a few more possibilities to configure the tile server:

`-b, --bind`
to specify the network interface to which to bind - default is every interface - I'd like to restrict this to e.g. 127.0.0.1

`-q, --quiet`
to disable the logging output

`-e, --etag`
to be able to provide an own time point/value for the HTTP chache-control header (somehow in the tileserver-gl there was a commit to remove the etag header, but I did not quite get it) As far as I understood, the generated and client-cached tiles should never be invalidated, unless a new version of the database is served, right?

**Comment by klokan** [comment]
Please open three individual pull requests for these features - with you changes proposed in the source code - so we can discuss on the individual features (and your code changes) separately.

**Comment by efi** [comment]
Ok, `--quiet`can be achieved by `export NODE_ENV=production` before executing the server. So no need for a code change (but maybe this should be documented somewhere).

**Comment by klokan** [comment]
Closing as resolved. Please continue on klokantech/tileserver-gl.
