### ISSUE TITLE
Load multiple tiles

### ISSUE THREAD

**Issue by Roozaay** [osm2vectortiles/tileserver-gl-light#6]
Hello,
I would like to load multiple mbtiles files while launching my server, like "tileserver-gl-light france.mbtiles italy.mbtiles".
Is it possible ?

**Comment by lukasmartinelli** [comment]
> Hello,
> I would like to load multiple mbtiles files while launching my server, like "tileserver-gl-light france.mbtiles italy.mbtiles".
> Is it possible ?

tileserver-gl-light has this restriction on purpose to make it easy to get started.
[tileserver-gl](https://github.com/klokantech/tileserver-gl) supports multiple data sources.

BTW. if they have the same vector tile schema (e.g. extracts of france and italy).
You can also merge them together and serve them.

Use the **patch** script from here https://github.com/mapbox/mbutil/blob/master/patch.

```
cp italy.mbtiles italy_and_france.mbtiles
patch france.mbtiles italy_and_france.mbtiles
```

**Comment by Roozaay** [comment]
Thanks for this quick answer, I will use the patch script !
