### ISSUE TITLE
Use my tileserver in QGIS

### ISSUE THREAD

**Issue by Roozaay** [osm2vectortiles/tileserver-gl-light#7]
Hello,
I order to do it with a distant server I actually try to link my mbtiles local server with QGIS 2.8 (I'm on Ubuntu).
The FAQ on your website say that it is possible but I can't find how...

**Comment by lukasmartinelli** [comment]
Only if you server raster tiles can you display it in QGIS.
And serving raster from GL styles can be done using (again 😉 ) [tileserver-gl](https://github.com/klokantech/tileserver-gl).

**Comment by Roozaay** [comment]
Okay thanks :wink:
